@startuml
'https://plantuml.com/class-diagram

+class AddItemController {
    +ItemTitle : TextField
    +ItemDescription : TextField
    +ItemDate : TextField
    -itemTitle : String
    -itemDescription : String
    -itemDate : String
    use : itemAttributes
    +ItemTitleEntered(actionevent : ActionEvent)
    +ItemDescEntered(actionevent : ActionEvent)
    +ItemDateEntered(actionevent : ActionEvent)
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +SaveItemPressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
}

+class ChangeScenes {
    +scene : Scene
    +stageScene(scene : Scene)
    +Change(view : ViewScenes)
}

+class CompleteController {
    +TitleDisplay : TextArea
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +Print(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
}

+class DeleteItemController {
    +ItemTitle : TextField
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +ItemTitlePressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
    +DisplayAllPressed(actionevent : ActionEvent)
}

+class DeleteListController {
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +ClearList(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
}

+class DisplayAllController {
    +TitleDisplay : TextArea
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    call : itemAttributes
    text : String
    +HelpPressed(actionevent : ActionEvent)
    +Print(actionevent : ActionEvent)
}

+class EditDetailsController {

    +oldTitle : TextField
    +oldDescription : TextField
    +oldDate : TextField
    +newTitle : TextField
    +newDescription : TextField
    +newDate : TextField

    -OldTitle : String
    -OldDescription : String
    -OlddueDate : String
    -NewTitle : String
    -NewDescription : String
    -NewdueDate : String

    call : itemAttributes
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +EditPressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
    +DisplayAllPressed(actionevent : ActionEvent)

    +NewItemTitleEntered(actionevent : ActionEvent)
    +NewItemDescEntered(actionevent : ActionEvent)
    +NewItemDateEntered(actionevent : ActionEvent)
    +OldItemTitleEntered(actionevent : ActionEvent)
    +OldItemDescEntered(actionevent : ActionEvent)
    +OldItemDateEntered(actionevent : ActionEvent)
}

+class HelpScreenController {
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
}

+class IncompleteController {
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
    +Print(actionevent : ActionEvent)
    o : int
    text : String
    TitleDisplay : TextArea
}

+class itemAttributes {
    +title : String
    +description : String
    +dueDate : String
    -ToDoListTitle : List<String>
    -ToDoListDescription : List<String>
    -ToDoListDueDate : List<String>
    +setToDoListTitle(ToDoListTitle : List<String>)
    +getToDoListTitle() : List<String>
    +setToDoListDescription(ToDoListDescription : List<String>)
    +getToDoListDescription() : List<String>
    +setToDoListDueDate(ToDoListDueDate : List<String>)
    +getToDoListDueDate() : List<String>
}

+class LaunchApp {
    main() : String[]
    start()
}

+class LaunchAppController {
    +ExitPressed(actionevent : ActionEvent)
    +DeleteToDoPressed(actionevent : ActionEvent)
    +EditToDoTitlePressed(actionevent : ActionEvent)
    +AddItemPressed(actionevent : ActionEvent)
    +DeleteItemPressed(actionevent : ActionEvent)
    +EditDescriptionPressed(actionevent : ActionEvent)
    +DueDatePressed(actionevent : ActionEvent)
    +SaveOneListPressed(actionevent : ActionEvent)
    +LoadOneListPressed(actionevent : ActionEvent)
    +DisplayAllItemsPressed(actionevent : ActionEvent)
    +DisplayCompletedPressed(actionevent : ActionEvent)
    +DisplayIncompletePressed(actionevent : ActionEvent)
    +MarkCompletePressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
}

+class LoadListController {
    file : Scanner
    +TitleDisplay : TextArea
    +fileName : TextField
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +fileNameTyped(actionevent : ActionEvent)
    +LoadPressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
}

+class MarkCompleteController {
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +DisplayAllPressed(actionevent : ActionEvent)
    +ItemTitleEntered(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
    +ItemTitle : TextField
}

+class SaveListController {
    +fileName : TextField
    +writer : FileWriter
    filename : String
    +MenuButtonPressed(actionevent : ActionEvent)
    +ExitPressed(actionevent : ActionEvent)
    +fileNamePressed(actionevent : ActionEvent)
    +SavePressed(actionevent : ActionEvent)
    +HelpPressed(actionevent : ActionEvent)
}

+enum ViewScenes {
    AddItem : File
    Complete : File
    DeleteItem : File
    DeleteList : File
    DisplayAll : File
    EditDetails : File
    HelpScreen : File
    Incomplete : File
    LaunchApp : File
    LoadList : File
    MarkComplete : File
    SaveOneList : File
    +file : String
    +getFile() : String
}

AddItemController <|-- LaunchApp
ChangeScenes <|-- LaunchApp
CompleteController <|-- LaunchApp
DeleteItemController <|-- LaunchApp
DeleteListController <|-- LaunchApp
DisplayAllController <|-- LaunchApp
EditDetailsController <|-- LaunchApp
HelpScreenController <|-- LaunchApp
IncompleteController <|-- LaunchApp
itemAttributes <|-- LaunchApp
LaunchAppController <|-- LaunchApp
LoadListController <|-- LaunchApp
MarkCompleteController <|-- LaunchApp
SaveListController <|-- LaunchApp
ViewScenes <|-- LaunchApp

@enduml